# Generated by Django 5.2.14 on 2026-05-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('origin_city', models.CharField(choices=[('Riverside', 'Riverside'), ('San Bernardino', 'San Bernardino'), ('Ontario', 'Ontario'), ('Long Beach', 'Long Beach'), ('Los Angeles', 'Los Angeles'), ('Anaheim', 'Anaheim'), ('Irvine', 'Irvine'), ('Fontana', 'Fontana'), ('Pomona', 'Pomona'), ('Corona', 'Corona')], max_length=100)),
                ('destination_city', models.CharField(choices=[('Riverside', 'Riverside'), ('San Bernardino', 'San Bernardino'), ('Ontario', 'Ontario'), ('Long Beach', 'Long Beach'), ('Los Angeles', 'Los Angeles'), ('Anaheim', 'Anaheim'), ('Irvine', 'Irvine'), ('Fontana', 'Fontana'), ('Pomona', 'Pomona'), ('Corona', 'Corona')], max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('typical_duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['route_code'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(db_index=True, max_length=10)),
                ('tracking_number', models.CharField(db_index=True, max_length=15)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['truck_id', '-timestamp'], name='shipments_t_truck_i_2310d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked up'), ('IN_TRANSIT', 'In transit'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=20)),
                ('origin_city', models.CharField(choices=[('Riverside', 'Riverside'), ('San Bernardino', 'San Bernardino'), ('Ontario', 'Ontario'), ('Long Beach', 'Long Beach'), ('Los Angeles', 'Los Angeles'), ('Anaheim', 'Anaheim'), ('Irvine', 'Irvine'), ('Fontana', 'Fontana'), ('Pomona', 'Pomona'), ('Corona', 'Corona')], max_length=100)),
                ('destination_city', models.CharField(choices=[('Riverside', 'Riverside'), ('San Bernardino', 'San Bernardino'), ('Ontario', 'Ontario'), ('Long Beach', 'Long Beach'), ('Los Angeles', 'Los Angeles'), ('Anaheim', 'Anaheim'), ('Irvine', 'Irvine'), ('Fontana', 'Fontana'), ('Pomona', 'Pomona'), ('Corona', 'Corona')], max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pieces', models.IntegerField()),
                ('shipment_date', models.DateField()),
                ('estimated_delivery', models.DateField()),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('is_delayed', models.BooleanField(default=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('carrier_tracking_number', models.CharField(blank=True, max_length=30, null=True)),
                ('proof_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipments.driver')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipments.route')),
            ],
            options={
                'ordering': ['-shipment_date', 'tracking_number'],
                'indexes': [models.Index(fields=['status'], name='shipments_s_status_536511_idx'), models.Index(fields=['shipment_date'], name='shipments_s_shipmen_0a5343_idx')],
            },
        ),
    ]
